version: '3.8'

services:
  sim:
    image: sim-nvidia-min:1.0.0
    build:
      context: .
      dockerfile: ./config/docker/ubuntu/sim.Dockerfile
    environment:
      - USER=root
      - DISPLAY=:1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "6080:6080"  # Porta para acessar o noVNC
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia