version: '3.8'

services:
  sim:
    image: sim-min:1.0.0
    build:
      context: .
      dockerfile: ./config/docker/ubuntu/sim.Dockerfile
    environment:
      - USER=root
      - DISPLAY=:1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "6080:6080"  # Porta para acessar o noVNC