version: '3.8'

services:
  sim:
    image: sim:1.0.0
    build:
      dockerfile: ./config/docker/ubuntu/sim.Dockerfile
    environment:
      - USER=root
      - DISPLAY=:1
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # - MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - /usr/lib/nvidia:/usr/lib/nvidia
      #- /usr/bin/nvidia-smi:/usr/bin/nvidia-smi
      # - /usr/bin/nvidia-debugdump:/usr/bin/nvidia-debugdump
      # - /usr/bin/nvidia-persistenced:/usr/bin/nvidia-persistenced
      # - /usr/bin/nvidia-cuda-mps-control:/usr/bin/nvidia-cuda-mps-control
      # - /usr/bin/nvidia-cuda-mps-server:/usr/bin/nvidia-cuda-mps-server
    ports:
      - "6080:6080"  # Porta para acessar o noVNC
      # - "5900:5900" # Porta para acessar VNC
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    # runtime: nvidia
    #network_mode: "host"